services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "blogtoscano2024"
      MYSQL_DATABASE: "pedrotoscano"
    ports:
      - "3000:3000"

  adminer:
    image: adminer
    ports:
      - 8080:8080
